import { createContext, useContext, useState, useEffect } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

// Translations
const translations = {
  ar: {
    // Navigation
    home: 'الرئيسية',
    stadiums: 'الملاعب',
    matches: 'المباريات',
    bookings: 'حجوزاتي',
    profile: 'الملف الشخصي',
    
    // Stadium Screen
    searchStadiums: 'البحث عن ملاعب',
    availableStadiums: 'الملاعب المتاحة',
    searching: 'جاري البحث...',
    noStadiumsFound: 'لم يتم العثور على ملاعب',
    retry: 'إعادة المحاولة',
    nearest: 'الأقرب',
    stadium: 'ملعب',
    rating: 'التقييم',
    km: 'كم',
    perHour: 'للساعة',
    description: 'الوصف',
    amenities: 'المرافق',
    pricePerHour: 'السعر للساعة',
    
    // Match Screen
    findMatch: 'البحث عن مباراة',
    createMatch: 'إنشاء مباراة',
    noMatchesFound: 'لا توجد مباريات',
    players: 'اللاعبين',
    spotsLeft: 'أماكن متبقية',
    spotsAvailable: 'أماكن متاحة',
    matchFull: 'المباراة ممتلئة',
    join: 'انضمام',
    joinMatch: 'انضمام للمباراة',
    organizer: 'المنظم',
    matchOrganizer: 'منظم المباراة',
    matchRules: 'قواعد المباراة',
    yourShare: 'حصتك',
    format: 'الصيغة',
    perPlayer: 'للاعب',
    matchSummary: 'ملخص المباراة',
    playersNeeded: 'اللاعبين المطلوبين',
    selectStadium: 'اختر الملعب',
    chooseNearestStadium: 'اختر أقرب ملعب',
    sortedByDistance: 'مرتبة حسب المسافة',
    skillLevel: 'مستوى المهارة',
    notes: 'ملاحظات',
    notesOptional: 'ملاحظات (اختياري)',
    anyAdditionalInfo: 'أي معلومات إضافية...',
    matchCreated: 'تم إنشاء المباراة',
    matchCreatedSuccess: 'تم إنشاء المباراة بنجاح',
    joinedSuccess: 'تم الانضمام للمباراة بنجاح',
    joinFailed: 'فشل الانضمام للمباراة',
    fillAllFields: 'يرجى ملء جميع الحقول المطلوبة',
    playersMustBeBetween: 'عدد اللاعبين يجب أن يكون بين',
    and: 'و',
    kmAway: 'كم',
    beOnTime: 'كن في الوقت (15 دقيقة قبل)',
    bringEquipment: 'أحضر معداتك',
    fairPlay: 'اللعب النظيف والاحترام',
    paymentBefore: 'الدفع قبل المباراة',
    
    // Booking Screen
    myBookings: 'حجوزاتي',
    noBookingsYet: 'لا توجد حجوزات',
    bookingsAppearHere: 'ستظهر حجوزاتك هنا',
    bookNow: 'احجز الآن',
    selectDate: 'اختر التاريخ',
    selectTime: 'اختر الوقت',
    duration: 'المدة',
    hour: 'ساعة',
    hours: 'ساعات',
    totalPrice: 'السعر الإجمالي',
    total: 'المجموع',
    confirmBooking: 'تأكيد الحجز',
    bookingSummary: 'ملخص الحجز',
    bookingCreated: 'تم إنشاء الحجز',
    payNow: 'ادفع الآن',
    payLater: 'ادفع لاحقاً',
    selectTimeSlot: 'يرجى اختيار وقت',
    
    // Profile Screen
    editProfile: 'تعديل الملف',
    settings: 'الإعدادات',
    language: 'اللغة',
    theme: 'المظهر',
    appearance: 'المظهر',
    darkMode: 'الوضع الداكن',
    lightMode: 'الوضع الفاتح',
    light: 'فاتح',
    dark: 'داكن',
    system: 'النظام',
    notifications: 'الإشعارات',
    helpSupport: 'المساعدة والدعم',
    about: 'حول التطبيق',
    logout: 'تسجيل الخروج',
    logoutConfirm: 'هل أنت متأكد من تسجيل الخروج؟',
    player: 'لاعب',
    version: 'الإصدار',
    
    // Auth
    login: 'تسجيل الدخول',
    signup: 'إنشاء حساب',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    name: 'الاسم',
    phone: 'رقم الهاتف',
    phoneOptional: 'رقم الهاتف (اختياري)',
    enterName: 'أدخل اسمك',
    enterEmail: 'أدخل بريدك الإلكتروني',
    enterPassword: 'أدخل كلمة المرور',
    createAccount: 'إنشاء حساب جديد',
    loginToAccount: 'تسجيل الدخول إلى حسابك',
    haveAccount: 'لديك حساب؟ تسجيل الدخول',
    noAccount: 'ليس لديك حساب؟ إنشاء حساب',
    fillRequiredFields: 'الرجاء ملء جميع الحقول المطلوبة',
    passwordMinLength: 'كلمة المرور يجب أن تكون 6 أحرف على الأقل',
    emailOrPasswordWrong: 'البريد الإلكتروني أو كلمة المرور غير صحيحة',
    emailExists: 'هذا البريد الإلكتروني مسجل مسبقاً',
    invalidEmail: 'يرجى إدخال بريد إلكتروني صحيح',
    serverError: 'خطأ في الخادم، يرجى المحاولة لاحقاً',
    connectionError: 'خطأ في الاتصال بالخادم',
    unexpectedError: 'حدث خطأ غير متوقع',
    testHint: 'للتجربة: استخدم أي بريد إلكتروني وكلمة مرور',
    continueWithGoogle: 'المتابعة مع Google',
    googleAuthError: 'فشل تسجيل الدخول بـ Google',
    
    // About Screen
    termsOfService: 'شروط الخدمة',
    privacyPolicy: 'سياسة الخصوصية',
    rateUs: 'قيم التطبيق',
    shareApp: 'شارك التطبيق',
    appDescription: 'احجز ملاعب كرة القدم وابحث عن مباريات مع لاعبين بمستواك. أسهل طريقة للعب كرة القدم في الجزائر.',
    madeWithLove: 'صنع بـ ❤️ في الجزائر',
    allRightsReserved: 'جميع الحقوق محفوظة',
    
    // Help & Support
    contactUs: 'اتصل بنا',
    callUs: 'اتصل بنا',
    whatsapp: 'واتساب',
    faq: 'الأسئلة الشائعة',
    howToBook: 'كيف أحجز ملعب؟',
    howToBookAnswer: 'تصفح الملاعب، اختر الوقت المناسب، وأكد حجزك.',
    canCancelBooking: 'هل يمكنني إلغاء الحجز؟',
    canCancelBookingAnswer: 'نعم، يمكنك الإلغاء قبل 24 ساعة من الموعد للحصول على استرداد كامل.',
    howToJoinMatch: 'كيف أنضم لمباراة؟',
    howToJoinMatchAnswer: 'اذهب إلى البحث عن مباراة، تصفح المباريات المتاحة، واضغط انضمام.',
    howPaymentsWork: 'كيف تعمل المدفوعات؟',
    howPaymentsWorkAnswer: 'ندعم الدفع نقداً في الملعب أو الدفع الإلكتروني عبر التطبيق.',
    
    // Common
    loading: 'جاري التحميل...',
    error: 'خطأ',
    success: 'تم بنجاح',
    done: 'تم',
    cancel: 'إلغاء',
    confirm: 'تأكيد',
    save: 'حفظ',
    delete: 'حذف',
    edit: 'تعديل',
    close: 'إغلاق',
    ok: 'حسناً',
    yes: 'نعم',
    no: 'لا',
    all: 'الكل',
    filter: 'تصفية',
    sort: 'ترتيب',
    search: 'بحث',
    date: 'التاريخ',
    time: 'الوقت',
    price: 'السعر',
    status: 'الحالة',
    
    // Status
    pending: 'قيد الانتظار',
    confirmed: 'مؤكد',
    cancelled: 'ملغي',
    completed: 'مكتمل',
    open: 'مفتوح',
    full: 'ممتلئ',
    paid: 'مدفوع',
    
    // Skill Levels
    beginner: 'مبتدئ',
    intermediate: 'متوسط',
    advanced: 'متقدم',
    professional: 'محترف',
    
    // Positions
    goalkeeper: 'حارس مرمى',
    defender: 'مدافع',
    midfielder: 'لاعب وسط',
    forward: 'مهاجم',
    preferredPositions: 'المراكز المفضلة',
    selectMultiplePositions: 'يمكنك اختيار أكثر من مركز',
    selectPosition: 'يرجى اختيار مركز واحد على الأقل',
    selectSkillLevel: 'يرجى اختيار مستوى المهارة',
    completeProfile: 'أكمل ملفك الشخصي',
    welcomeUser: 'مرحباً! اختر تفضيلاتك',
    continue: 'متابعة',
    
    // Field Sizes
    fieldSize: 'حجم الملعب',
    
    // Premium UI
    welcome: 'مرحباً',
    findYourGame: 'ابحث عن مباراتك',
    matchesAvailable: 'مباريات متاحة',
    viewDetails: 'عرض التفاصيل',
    joining: 'جاري الانضمام',
    or: 'أو',
    
    // Match Types
    selectMatchType: 'اختر نوع المباراة',
    selectMatchTypeDesc: 'هل تبحث عن لاعبين أم فريق منافس؟',
    findPlayers: 'البحث عن لاعبين',
    findPlayersDesc: 'أنشئ مباراة وابحث عن لاعبين للانضمام',
    findTeam: 'البحث عن فريق',
    findTeamDesc: 'ابحث عن فريق منافس لمباراتك',
    teamMatch: 'مباراة فرق',
    teamVsTeam: 'فريق ضد فريق',
    findOpponent: 'البحث عن منافس',
    findOpponentDesc: 'ابحث عن فريق آخر للعب ضده',
    yourTeamName: 'اسم فريقك',
    enterTeamName: 'أدخل اسم الفريق',
    teamLevel: 'مستوى الفريق',
    teamMatchNotes: 'معلومات إضافية عن فريقك...',
    yourTeam: 'فريقك',
    lookingFor: 'يبحث عن',
    opponentTeam: 'فريق منافس',
    teamMatchCreatedSuccess: 'تم إنشاء طلب المباراة بنجاح',
    lookingForOpponent: 'يبحث عن منافس',
    opponentFound: 'تم إيجاد منافس',
    challenge: 'تحدي',
    teams: 'الفرق',
  },
  
  en: {
    // Navigation
    home: 'Home',
    stadiums: 'Stadiums',
    matches: 'Matches',
    bookings: 'My Bookings',
    profile: 'Profile',
    
    // Stadium Screen
    searchStadiums: 'Search Stadiums',
    availableStadiums: 'Available Stadiums',
    searching: 'Searching...',
    noStadiumsFound: 'No stadiums found',
    retry: 'Retry',
    nearest: 'Nearest',
    stadium: 'Stadium',
    rating: 'Rating',
    km: 'km',
    perHour: '/hour',
    description: 'Description',
    amenities: 'Amenities',
    pricePerHour: 'Price per hour',
    
    // Match Screen
    findMatch: 'Find a Match',
    createMatch: 'Create Match',
    noMatchesFound: 'No matches found',
    players: 'Players',
    spotsLeft: 'spots left',
    spotsAvailable: 'spots available',
    matchFull: 'Match Full',
    join: 'Join',
    joinMatch: 'Join Match',
    organizer: 'Organizer',
    matchOrganizer: 'Match Organizer',
    matchRules: 'Match Rules',
    yourShare: 'Your share',
    format: 'Format',
    perPlayer: 'Per Player',
    matchSummary: 'Match Summary',
    playersNeeded: 'Players Needed',
    selectStadium: 'Select Stadium',
    chooseNearestStadium: 'Choose nearest stadium',
    sortedByDistance: 'Sorted by distance (nearest first)',
    skillLevel: 'Skill Level',
    notes: 'Notes',
    notesOptional: 'Notes (Optional)',
    anyAdditionalInfo: 'Any additional info...',
    matchCreated: 'Match Created',
    matchCreatedSuccess: 'Match created successfully',
    joinedSuccess: 'Successfully joined the match',
    joinFailed: 'Failed to join match',
    fillAllFields: 'Please fill all required fields',
    playersMustBeBetween: 'Players must be between',
    and: 'and',
    kmAway: 'km away',
    beOnTime: 'Be on time (15 min before)',
    bringEquipment: 'Bring your own equipment',
    fairPlay: 'Fair play and respect',
    paymentBefore: 'Payment before match',
    
    // Booking Screen
    myBookings: 'My Bookings',
    noBookingsYet: 'No Bookings Yet',
    bookingsAppearHere: 'Your stadium reservations will appear here',
    bookNow: 'Book Now',
    selectDate: 'Select Date',
    selectTime: 'Select Time',
    duration: 'Duration',
    hour: 'hour',
    hours: 'hours',
    totalPrice: 'Total Price',
    total: 'Total',
    confirmBooking: 'Confirm Booking',
    bookingSummary: 'Booking Summary',
    bookingCreated: 'Booking Created!',
    payNow: 'Pay Now',
    payLater: 'Pay Later',
    selectTimeSlot: 'Please select a time slot',
    
    // Profile Screen
    editProfile: 'Edit Profile',
    settings: 'Settings',
    language: 'Language',
    theme: 'Theme',
    appearance: 'Appearance',
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    light: 'Light',
    dark: 'Dark',
    system: 'System',
    notifications: 'Notifications',
    helpSupport: 'Help & Support',
    about: 'About',
    logout: 'Logout',
    logoutConfirm: 'Are you sure you want to logout?',
    player: 'Player',
    version: 'Version',
    
    // Auth
    login: 'Login',
    signup: 'Sign Up',
    email: 'Email',
    password: 'Password',
    name: 'Name',
    phone: 'Phone Number',
    phoneOptional: 'Phone Number (Optional)',
    enterName: 'Enter your name',
    enterEmail: 'Enter your email',
    enterPassword: 'Enter password',
    createAccount: 'Create a new account',
    loginToAccount: 'Login to your account',
    haveAccount: 'Have an account? Login',
    noAccount: "Don't have an account? Sign Up",
    fillRequiredFields: 'Please fill all required fields',
    passwordMinLength: 'Password must be at least 6 characters',
    emailOrPasswordWrong: 'Email or password is incorrect',
    emailExists: 'This email is already registered',
    invalidEmail: 'Please enter a valid email address',
    serverError: 'Server error, please try again later',
    connectionError: 'Connection error',
    unexpectedError: 'An unexpected error occurred',
    testHint: 'For testing: use any email and password',
    continueWithGoogle: 'Continue with Google',
    googleAuthError: 'Google sign in failed',
    
    // About Screen
    termsOfService: 'Terms of Service',
    privacyPolicy: 'Privacy Policy',
    rateUs: 'Rate Us',
    shareApp: 'Share App',
    appDescription: 'Book football stadiums and find matches with players at your skill level. The easiest way to play football in Algeria.',
    madeWithLove: 'Made with ❤️ in Algeria',
    allRightsReserved: 'All rights reserved',
    
    // Help & Support
    contactUs: 'Contact Us',
    callUs: 'Call Us',
    whatsapp: 'WhatsApp',
    faq: 'FAQ',
    howToBook: 'How do I book a stadium?',
    howToBookAnswer: 'Browse stadiums, select your preferred time slot, and confirm your booking.',
    canCancelBooking: 'Can I cancel my booking?',
    canCancelBookingAnswer: 'Yes, you can cancel up to 24 hours before the scheduled time for a full refund.',
    howToJoinMatch: 'How do I join a match?',
    howToJoinMatchAnswer: 'Go to Find Match, browse available matches, and tap Join to request to join.',
    howPaymentsWork: 'How do payments work?',
    howPaymentsWorkAnswer: 'We support cash payment at the stadium or online payment through the app.',
    
    // Common
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    done: 'Done!',
    cancel: 'Cancel',
    confirm: 'Confirm',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    close: 'Close',
    ok: 'OK',
    yes: 'Yes',
    no: 'No',
    all: 'All',
    filter: 'Filter',
    sort: 'Sort',
    search: 'Search',
    date: 'Date',
    time: 'Time',
    price: 'Price',
    status: 'Status',
    
    // Status
    pending: 'Pending',
    confirmed: 'Confirmed',
    cancelled: 'Cancelled',
    completed: 'Completed',
    open: 'Open',
    full: 'Full',
    paid: 'Paid',
    
    // Skill Levels
    beginner: 'Beginner',
    intermediate: 'Intermediate',
    advanced: 'Advanced',
    professional: 'Professional',
    
    // Positions
    goalkeeper: 'Goalkeeper',
    defender: 'Defender',
    midfielder: 'Midfielder',
    forward: 'Forward',
    preferredPositions: 'Preferred Positions',
    selectMultiplePositions: 'You can select multiple positions',
    selectPosition: 'Please select at least one position',
    selectSkillLevel: 'Please select your skill level',
    completeProfile: 'Complete Your Profile',
    welcomeUser: 'Welcome! Select your preferences',
    continue: 'Continue',
    
    // Field Sizes
    fieldSize: 'Field Size',
    
    // Premium UI
    welcome: 'Welcome',
    findYourGame: 'Find your game',
    matchesAvailable: 'matches available',
    viewDetails: 'View Details',
    joining: 'Joining',
    or: 'or',
    
    // Match Types
    selectMatchType: 'Select Match Type',
    selectMatchTypeDesc: 'Are you looking for players or an opponent team?',
    findPlayers: 'Find Players',
    findPlayersDesc: 'Create a match and find players to join',
    findTeam: 'Find a Team',
    findTeamDesc: 'Find an opponent team for your match',
    teamMatch: 'Team Match',
    teamVsTeam: 'Team vs Team',
    findOpponent: 'Find Opponent',
    findOpponentDesc: 'Find another team to play against',
    yourTeamName: 'Your Team Name',
    enterTeamName: 'Enter team name',
    teamLevel: 'Team Level',
    teamMatchNotes: 'Additional info about your team...',
    yourTeam: 'Your Team',
    lookingFor: 'Looking for',
    opponentTeam: 'Opponent Team',
    teamMatchCreatedSuccess: 'Match request created successfully',
    lookingForOpponent: 'Looking for opponent',
    opponentFound: 'Opponent found',
    challenge: 'Challenge',
    teams: 'Teams',
  },
  
  fr: {
    // Navigation
    home: 'Accueil',
    stadiums: 'Stades',
    matches: 'Matchs',
    bookings: 'Mes Réservations',
    profile: 'Profil',
    
    // Stadium Screen
    searchStadiums: 'Rechercher des stades',
    availableStadiums: 'Stades disponibles',
    searching: 'Recherche en cours...',
    noStadiumsFound: 'Aucun stade trouvé',
    retry: 'Réessayer',
    nearest: 'Le plus proche',
    stadium: 'Stade',
    rating: 'Note',
    km: 'km',
    perHour: '/heure',
    description: 'Description',
    amenities: 'Équipements',
    pricePerHour: 'Prix par heure',
    
    // Match Screen
    findMatch: 'Trouver un match',
    createMatch: 'Créer un match',
    noMatchesFound: 'Aucun match trouvé',
    players: 'Joueurs',
    spotsLeft: 'places restantes',
    spotsAvailable: 'places disponibles',
    matchFull: 'Match complet',
    join: 'Rejoindre',
    joinMatch: 'Rejoindre le match',
    organizer: 'Organisateur',
    matchOrganizer: 'Organisateur du match',
    matchRules: 'Règles du match',
    yourShare: 'Votre part',
    format: 'Format',
    perPlayer: 'Par joueur',
    matchSummary: 'Résumé du match',
    playersNeeded: 'Joueurs nécessaires',
    selectStadium: 'Sélectionner un stade',
    chooseNearestStadium: 'Choisir le stade le plus proche',
    sortedByDistance: 'Trié par distance (le plus proche en premier)',
    skillLevel: 'Niveau de compétence',
    notes: 'Notes',
    notesOptional: 'Notes (Optionnel)',
    anyAdditionalInfo: 'Informations supplémentaires...',
    matchCreated: 'Match créé',
    matchCreatedSuccess: 'Match créé avec succès',
    joinedSuccess: 'Vous avez rejoint le match avec succès',
    joinFailed: 'Échec de rejoindre le match',
    fillAllFields: 'Veuillez remplir tous les champs requis',
    playersMustBeBetween: 'Le nombre de joueurs doit être entre',
    and: 'et',
    kmAway: 'km',
    beOnTime: 'Soyez à l\'heure (15 min avant)',
    bringEquipment: 'Apportez votre équipement',
    fairPlay: 'Fair-play et respect',
    paymentBefore: 'Paiement avant le match',
    
    // Booking Screen
    myBookings: 'Mes Réservations',
    noBookingsYet: 'Pas encore de réservations',
    bookingsAppearHere: 'Vos réservations apparaîtront ici',
    bookNow: 'Réserver',
    selectDate: 'Sélectionner la date',
    selectTime: "Sélectionner l'heure",
    duration: 'Durée',
    hour: 'heure',
    hours: 'heures',
    totalPrice: 'Prix total',
    total: 'Total',
    confirmBooking: 'Confirmer la réservation',
    bookingSummary: 'Résumé de la réservation',
    bookingCreated: 'Réservation créée!',
    payNow: 'Payer maintenant',
    payLater: 'Payer plus tard',
    selectTimeSlot: 'Veuillez sélectionner un créneau horaire',
    
    // Profile Screen
    editProfile: 'Modifier le profil',
    settings: 'Paramètres',
    language: 'Langue',
    theme: 'Thème',
    appearance: 'Apparence',
    darkMode: 'Mode sombre',
    lightMode: 'Mode clair',
    light: 'Clair',
    dark: 'Sombre',
    system: 'Système',
    notifications: 'Notifications',
    helpSupport: 'Aide et support',
    about: 'À propos',
    logout: 'Déconnexion',
    logoutConfirm: 'Êtes-vous sûr de vouloir vous déconnecter?',
    player: 'Joueur',
    version: 'Version',
    
    // Auth
    login: 'Connexion',
    signup: "S'inscrire",
    email: 'Email',
    password: 'Mot de passe',
    name: 'Nom',
    phone: 'Numéro de téléphone',
    phoneOptional: 'Numéro de téléphone (Optionnel)',
    enterName: 'Entrez votre nom',
    enterEmail: 'Entrez votre email',
    enterPassword: 'Entrez le mot de passe',
    createAccount: 'Créer un nouveau compte',
    loginToAccount: 'Connectez-vous à votre compte',
    haveAccount: 'Vous avez un compte? Connexion',
    noAccount: "Pas de compte? S'inscrire",
    fillRequiredFields: 'Veuillez remplir tous les champs requis',
    passwordMinLength: 'Le mot de passe doit contenir au moins 6 caractères',
    emailOrPasswordWrong: 'Email ou mot de passe incorrect',
    emailExists: 'Cet email est déjà enregistré',
    invalidEmail: 'Veuillez entrer une adresse email valide',
    serverError: 'Erreur serveur, veuillez réessayer plus tard',
    connectionError: 'Erreur de connexion',
    unexpectedError: 'Une erreur inattendue s\'est produite',
    testHint: 'Pour tester: utilisez n\'importe quel email et mot de passe',
    continueWithGoogle: 'Continuer avec Google',
    googleAuthError: 'Échec de la connexion Google',
    
    // About Screen
    termsOfService: 'Conditions d\'utilisation',
    privacyPolicy: 'Politique de confidentialité',
    rateUs: 'Notez-nous',
    shareApp: 'Partager l\'application',
    appDescription: 'Réservez des stades de football et trouvez des matchs avec des joueurs de votre niveau. Le moyen le plus simple de jouer au football en Algérie.',
    madeWithLove: 'Fait avec ❤️ en Algérie',
    allRightsReserved: 'Tous droits réservés',
    
    // Help & Support
    contactUs: 'Contactez-nous',
    callUs: 'Appelez-nous',
    whatsapp: 'WhatsApp',
    faq: 'FAQ',
    howToBook: 'Comment réserver un stade?',
    howToBookAnswer: 'Parcourez les stades, sélectionnez votre créneau horaire préféré et confirmez votre réservation.',
    canCancelBooking: 'Puis-je annuler ma réservation?',
    canCancelBookingAnswer: 'Oui, vous pouvez annuler jusqu\'à 24 heures avant l\'heure prévue pour un remboursement complet.',
    howToJoinMatch: 'Comment rejoindre un match?',
    howToJoinMatchAnswer: 'Allez dans Trouver un match, parcourez les matchs disponibles et appuyez sur Rejoindre.',
    howPaymentsWork: 'Comment fonctionnent les paiements?',
    howPaymentsWorkAnswer: 'Nous acceptons le paiement en espèces au stade ou le paiement en ligne via l\'application.',
    
    // Common
    loading: 'Chargement...',
    error: 'Erreur',
    success: 'Succès',
    done: 'Terminé!',
    cancel: 'Annuler',
    confirm: 'Confirmer',
    save: 'Enregistrer',
    delete: 'Supprimer',
    edit: 'Modifier',
    close: 'Fermer',
    ok: 'OK',
    yes: 'Oui',
    no: 'Non',
    all: 'Tous',
    filter: 'Filtrer',
    sort: 'Trier',
    search: 'Rechercher',
    date: 'Date',
    time: 'Heure',
    price: 'Prix',
    status: 'Statut',
    
    // Status
    pending: 'En attente',
    confirmed: 'Confirmé',
    cancelled: 'Annulé',
    completed: 'Terminé',
    open: 'Ouvert',
    full: 'Complet',
    paid: 'Payé',
    
    // Skill Levels
    beginner: 'Débutant',
    intermediate: 'Intermédiaire',
    advanced: 'Avancé',
    professional: 'Professionnel',
    
    // Positions
    goalkeeper: 'Gardien',
    defender: 'Défenseur',
    midfielder: 'Milieu',
    forward: 'Attaquant',
    preferredPositions: 'Positions préférées',
    selectMultiplePositions: 'Vous pouvez sélectionner plusieurs positions',
    selectPosition: 'Veuillez sélectionner au moins une position',
    selectSkillLevel: 'Veuillez sélectionner votre niveau',
    completeProfile: 'Complétez votre profil',
    welcomeUser: 'Bienvenue! Sélectionnez vos préférences',
    continue: 'Continuer',
    
    // Field Sizes
    fieldSize: 'Taille du terrain',
    
    // Premium UI
    welcome: 'Bienvenue',
    findYourGame: 'Trouvez votre match',
    matchesAvailable: 'matchs disponibles',
    viewDetails: 'Voir les détails',
    joining: 'En cours',
    or: 'ou',
    
    // Match Types
    selectMatchType: 'Sélectionner le type de match',
    selectMatchTypeDesc: 'Cherchez-vous des joueurs ou une équipe adverse?',
    findPlayers: 'Trouver des joueurs',
    findPlayersDesc: 'Créez un match et trouvez des joueurs',
    findTeam: 'Trouver une équipe',
    findTeamDesc: 'Trouvez une équipe adverse pour votre match',
    teamMatch: 'Match d\'équipe',
    teamVsTeam: 'Équipe vs Équipe',
    findOpponent: 'Trouver un adversaire',
    findOpponentDesc: 'Trouvez une autre équipe pour jouer contre',
    yourTeamName: 'Nom de votre équipe',
    enterTeamName: 'Entrez le nom de l\'équipe',
    teamLevel: 'Niveau de l\'équipe',
    teamMatchNotes: 'Infos supplémentaires sur votre équipe...',
    yourTeam: 'Votre équipe',
    lookingFor: 'Recherche',
    opponentTeam: 'Équipe adverse',
    teamMatchCreatedSuccess: 'Demande de match créée avec succès',
    lookingForOpponent: 'Recherche d\'adversaire',
    opponentFound: 'Adversaire trouvé',
    challenge: 'Défier',
    teams: 'Équipes',
  },
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');
  const [isRTL, setIsRTL] = useState(false);

  useEffect(() => {
    loadLanguage();
  }, []);

  const loadLanguage = async () => {
    try {
      const savedLang = await AsyncStorage.getItem('appLanguage');
      if (savedLang) {
        setLanguage(savedLang);
        setIsRTL(savedLang === 'ar');
      }
    } catch (error) {
      console.log('Error loading language:', error);
    }
  };

  const changeLanguage = async (lang) => {
    try {
      await AsyncStorage.setItem('appLanguage', lang);
      setLanguage(lang);
      setIsRTL(lang === 'ar');
    } catch (error) {
      console.log('Error saving language:', error);
    }
  };

  const t = (key) => {
    return translations[language]?.[key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
